repos:
  - repo: https://github.com/humitos/mirrors-autoflake.git
    rev: v1.1
    hooks:
    - id: autoflake
      args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config
  - repo: https://github.com/pycqa/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
        name: isort (python)
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
